In [17]:
# Nesta seção vamos aprender a criar arrays

# A primeira coisa para se fazer quando querermos criar arrays é importar a biblioteca numpy

import numpy as np # Utilizamos um alias para apelidar a biblioteca.

# Uma maneira de criar um array é convertendo uma lista para array

lista = [1, 2, 3, 4, 5]

array = np.array(lista)

# Exibindo array

print(array)

[1 2 3 4 5]


In [18]:
# Utilizando o método type() para exibir o tipo de dado dessa variável

type(array)

numpy.ndarray

In [19]:
array

array([1, 2, 3, 4, 5])

In [20]:
# Declarando outras variáveis

lista_pares = [22, 24, 26, 28, 30]

listas = [lista, lista_pares]

print(listas)

[[1, 2, 3, 4, 5], [22, 24, 26, 28, 30]]


In [21]:
# Com listas de listas podemos fazer arrays multidimensionais

array_multidimensional = np.array(listas)

print(array_multidimensional)

[[ 1  2  3  4  5]
 [22 24 26 28 30]]


In [22]:
array_multidimensional

array([[ 1,  2,  3,  4,  5],
       [22, 24, 26, 28, 30]])

In [23]:
array_multidimensional.shape

(2, 5)

In [24]:
array.shape

(5,)

In [25]:
# O método shape exibe a forma do array

# O método dtype exibi o tipo de dado do array

array_multidimensional.dtype

dtype('int32')

In [26]:
array.dtype

dtype('int32')

In [30]:
# Também existem casos especiais de array.

# Array com zeros

array_zeros = np.zeros(2)

print(array_zeros)

[0. 0.]


In [31]:
array_zeros.dtype

dtype('float64')

In [32]:
# Array de um

array_ums = np.ones(5)

print(array_ums)

[1. 1. 1. 1. 1.]


In [33]:
array_ums.dtype

dtype('float64')

# Brincando

In [48]:
lista_idade = [10, 20, 30, 40, 50]

transformacao = np.array(lista_idade) # Transformando uma lista em um array

print('Array:', transformacao)
print('Tipo:', type(transformacao))
print('Variável:', transformacao.dtype)

lista_numeros = [1, 2, 3, 4, 5]

transformacao_numeros = np.array(lista_numeros) # Transformando uma lista em um array

print('\nArray:', transformacao_numeros)
print('Tipo:', type(transformacao_numeros))
print('Variável:', transformacao_numeros.dtype)

# Criando array multidimensional

lista_uniao = [lista_idade, lista_numeros]

array_multi = np.array(lista_uniao)
 
print('\nArray:', array_multi)
print('Tipo:', type(array_multi))
print('Variável:', array_multi.dtype)

# Exibindo formatos dos arrys

print('\nShapes:\n')
print(transformacao.shape)
print(transformacao_numeros.shape)
print(array_multi.shape)

# Criando array com zeros

array_com_zeros = np.zeros([2,2])

print('\nArray com zeros:', array_com_zeros)

# Criando array com um's

array_com_ums = np.ones([5])

print('\nArray com ums:', array_com_ums)

# O argumento desses métodos recebe uma lista informando a quantidade de elementos nas dimensões

Array: [10 20 30 40 50]
Tipo: <class 'numpy.ndarray'>
Variável: int32

Array: [1 2 3 4 5]
Tipo: <class 'numpy.ndarray'>
Variável: int32

Array: [[10 20 30 40 50]
 [ 1  2  3  4  5]]
Tipo: <class 'numpy.ndarray'>
Variável: int32

Shapes:

(5,)
(5,)
(2, 5)

Array com zeros: [[0. 0.]
 [0. 0.]]

Array com ums: [1. 1. 1. 1. 1.]


In [64]:
# Também podemos criar arrays vazios que é a mesma coisa de se criar um array de zeros

array_vazio = np.empty(4)

print(array_vazio)

[0. 0. 0. 0.]


In [66]:
# Matriz identidade - Possui um's na diagonal e o resto são zeros.

np.eye(5) # Formara uma matriz quadrada

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
# Método arange() - Com ele você pode inserir um começo, uma parada e um tamanho.

# Ele vai retornar uniformemente os valores espaçados dentro desse intervalo dado.

np.arange(5)

array([0, 1, 2, 3, 4])

In [68]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])