# Usando arrays e escalares

Podemos realizar operações matemáticas com escalares no array.

In [24]:
import numpy as np

In [25]:
5/2

2.5

In [26]:
5//2

2

In [27]:
5.0/2

2.5

In [28]:
5/2.0

2.5

In [29]:
from __future__ import division

5/2

2.5

In [30]:
array = np.array([[1,2,3,4], [8,9,10,11]])

In [31]:
array

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [32]:
array * array

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [33]:
array + array

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [34]:
array - array

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
array // array

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [36]:
array / array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
1 / array

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [38]:
array ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)