In [2]:
import numpy as np

array_simples = np.arange(0,11,1)

In [3]:
array_simples

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array_simples[1:4]

array([1, 2, 3])

In [5]:
array_simples[-1]

10

In [6]:
array_simples[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
array_simples[0:5]

array([0, 1, 2, 3, 4])

In [8]:
# Os valores do intervalo 0:5 serão modificados

array_simples[0:5] = [1000] # Todos os valores desse intervalo irão valer 1000

In [9]:
array_simples

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [10]:
array_simples[0:5] = [1, 2, 3, 4, 8]

In [11]:
array_simples

array([ 1,  2,  3,  4,  8,  5,  6,  7,  8,  9, 10])

In [12]:
array = np.arange(0, 11)

In [13]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Podemos fazer um slice no array

fatiamento_do_array = array[0:6]

fatiamento_do_array

array([0, 1, 2, 3, 4, 5])

In [15]:
fatiamento_do_array[0:3]

array([0, 1, 2])

In [16]:
fatiamento_do_array[::] = 99 #Todos os elementos desse array irão valer 99

In [17]:
fatiamento_do_array

array([99, 99, 99, 99, 99, 99])

In [18]:
array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
# Note que as mudançãs também ocorreram no array original

# Não mudamos os valores apenas em fatiamento_do_array??

# Bom, no numpy esses dados não são copiados...

# O fatiamento_do_array é apenas uma visão da matriz original. É uma view do array original.

# Então isso evito muitos problemas de memória.

# Dessa forma você não tem várias cópias do seu array em memória.

# Você tem apenas uma cópia do seu array.

# Se você pegar fatias dele e mudar coisas, então isso afetará o array original. 

# Então, isso é algo para realmente se ter em mente quando você está trabalhando com arrays.

# Caso não queira que isso aconteceça, você tem que ser explícito.

array_copia = array.copy() # Utilizar o método copy() para copiar o array orifinal para um outro array

In [20]:
array_copia

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
fatiamente_array_copia = array_copia[0:6]

In [23]:
fatiamente_array_copia

array([99, 99, 99, 99, 99, 99])

In [25]:
fatiamente_array_copia[::] = [0, 1, 2, 3, 4, 5] 

In [26]:
fatiamente_array_copia

array([0, 1, 2, 3, 4, 5])

In [27]:
array_copia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
# Indexando em um array 2D

array_2D = np.array(([50,10,15], [20, 25, 30], [35, 40, 45]))

In [32]:
array_2D

array([[50, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
array_2D[0]

array([50, 10, 15])

In [35]:
array_2D[1]

array([20, 25, 30])

In [36]:
array_2D[2]

array([35, 40, 45])

In [38]:
array_2D[0][0:2]

array([50, 10])

In [41]:
array_2D[2][1:3]

array([40, 45])

In [43]:
array_2D[1][1] # tradução - [linha][coluna]

25

In [50]:
array_2D[1:3][1:3]

array([[35, 40, 45]])

In [51]:
array_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [53]:
array_2D[:1,1:]

array([[10, 15]])

In [55]:
array_2D[0:3,0:1]

array([[50],
       [20],
       [35]])

In [56]:
array_2D_zeros = np.zeros([10,10])

In [57]:
c

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
array_2D_zeros = np.zeros((10,10))

In [60]:
array_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
tamanho_array = len(array_2D_zeros)

In [62]:
tamanho_array

10

In [63]:
tamanho_array = array_2D_zeros.shape

In [64]:
tamanho_array

(10, 10)

In [67]:
tamanho_array = array_2D_zeros.shape[1]

In [68]:
tamanho_array

10

In [74]:
for elemento in range(len(array_2D_zeros)):
    array_2D_zeros[elemento] = elemento

In [75]:
array_2D_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [76]:
array_2D_zeros[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [77]:
array_2D_zeros[[8,4,9,7]]

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [71]:
for elemento in range(len(array_2D_zeros)):
    array_2D_zeros[elemento] = 1

In [72]:
array_2D_zeros

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])