In [1]:
import numpy as np

In [2]:
array = np.arange(11) # Este array é um array unidimensional - Possui a aparência de um vetor - Seu range é de 0 - 10

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Funções Universais são funções básicas que você pode aplicar a todos os valores em um array.

# Exemplo: podemos tirar a raiz quadrada dos elementos de um array.

np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
# Também podemos aplicar o exponencial. Exponencial elevado a zero é um.

np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
# Existem também funções binárias. Isso exigirá duas matrizes para fazer sentido.

# Vamos criar um array aleatório.

A = np.random.randn(10) # Random distirbuição normal.

In [7]:
A

array([-0.52017751, -0.70431525, -0.61985822,  0.50100646, -0.99616048,
       -0.50657399, -1.47912852,  0.57975436, -1.68139989,  1.08571804])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-0.33368883, -1.25929993, -0.49926076, -0.53802473, -1.55917853,
       -0.72533211,  0.25068667,  1.30315047, -2.33992938, -1.52681166])

In [10]:
# Binary Functions

np.add(A, B) # Isso vai somar todos os valores A para todos os valores de B.

array([-0.85386634, -1.96361518, -1.11911898, -0.03701827, -2.55533902,
       -1.2319061 , -1.22844185,  1.88290483, -4.02132927, -0.44109363])

In [11]:
# Outra coisa que podemos fazer é encontrar o máximo e o mínimo entre dois arrays.

np.maximum(A, B) # Isso vai encontrar o máximo entre os dois valores de matriz.

# Irá comparada os valores em cada índice e retorna o resultado do maior.

array([-0.33368883, -0.70431525, -0.49926076,  0.50100646, -0.99616048,
       -0.50657399,  0.25068667,  1.30315047, -1.68139989,  1.08571804])

In [12]:
np.minimum(A,B) # Funciona como o maximum(), porém retorna o mínimo.

array([-0.52017751, -1.25929993, -0.61985822, -0.53802473, -1.55917853,
       -0.72533211, -1.47912852,  0.57975436, -2.33992938, -1.52681166])

In [13]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#avaible-ufuncs'

In [14]:
import webbrowser
webbrowser.open(website)

True

In [ ]:
# O site acima é o site da documentação das funções universais no numpy.